### ISSUE TITLE
Parser doesn't handle lines starting with spaces

### ISSUE THREAD

**Issue by rachitnigam** [plasma-umass/compsci631#10]
The parser for the program (specs and sketches) fails on cmd which start with spaces. Failed on this:

```
  y=x;
    y=x;
```

**Comment by arjunguha** [comment]
Please fix this problem. Thanks.

**Comment by baxtersa** [comment]
Fixed by 6ce6ea8

**Comment by arjunguha** [comment]
Oh no. I meant Rachit. But thanks!
